---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backuppc
  namespace: devops
spec:
  resources:
    requests:
      storage: 50Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storage
