apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-exporter
  name: redis-exporter
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 9121
    protocol: TCP
    targetPort: 9121
  selector:
    app: redis-exporter
  type: ClusterIP
