---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexus
  namespace: devops
  labels:
    app: nexus
spec:
  ingressClassName: nginx
  rules:
  - host: nexus.github.icu
    http:
      paths:
      - backend:
          service:
            name: nexus
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - nexus.github.icu
    secretName: github-tls
