---
apiVersion: v1
kind: Service
metadata:
  name: mozilla-send
  namespace: devops
  labels:
    app: mozilla-send
spec:
  selector:
    app: mozilla-send
  type: ClusterIP
  ports:
    - port: 1443
      name: web
      targetPort: 1443
      protocol: TCP
