---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: collectd-exporter
  name: collectd-exporter
  namespace: monitoring
spec:
  ports:
  - name: collectd-exporter
    port: 9103
    protocol: TCP
    targetPort: 9103
  selector:
    app: collectd-exporter
  type: ClusterIP
