---
apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: monitoring
  labels:
    app: node-exporter
spec:
  sessionAffinity: ClientIP
  selector:
    app: node-exporter
  type: NodePort
  ports:
    - name: metrics
      protocol: TCP
      port: 9100
      targetPort: 9100
      nodePort: 30000
