apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: windows-data
  namespace: devops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 70Gi
  storageClassName: moosefs-storage
