---
apiVersion: v1
kind: Service
metadata:
  name: jira
  namespace: atlassian
  labels:
    app: jira
spec:
  selector:
    app: jira
  type: ClusterIP
  ports:
    - port: 8080
      name: web
      targetPort: 8080
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jira
  namespace: atlassian
  labels:
    app: jira
spec:
  ingressClassName: nginx
  rules:
  - host: jira.github.icu
    http:
      paths:
      - backend:
          service:
            name: jira
            port:
              number: 8080
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - jira.github.icu
    secretName: github-tls
