apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8m
  namespace: k8m
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storage
