---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storage

