apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: categraf
  name: categraf
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: categraf
  template:
    metadata:
      labels:
        app: categraf
    spec:
      containers:
      - name: categraf
        env:
          - name: HOSTENAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          - name: HOSTIP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.hostIP
          - name: WAIT_HOSTS
            value: nightingale:17000, nightingale:20090
          - name: TZ
            value: Asia/Shanghai
        image: flashcatcloud/categraf:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 1Gi
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
        - name: categraf-config
          mountPath: /etc/categraf/conf
        - name: input-config
          mountPath: /etc/categraf/conf/input.vsphere
#      initContainers:
#        - name: create-input-dir
#          image: busybox
#          command: [mkdir, /etc/categraf/input.vsphere, -p]
#          volumeMounts:
#            - name: categraf-config
#              mountPath: /etc/categraf/conf
      volumes:
      - name: localtime
        hostPath:
          path: /etc/localtime
          type: ""
      - name: categraf-config
        configMap:
          defaultMode: 420
          name: categraf-config
          items:
          - key: config.toml
            path: config.toml
      - name: input-config
        configMap:
          defaultMode: 420
          name: input-config
          items:
          - key: vsphere.toml
            path: vsphere.toml
