---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: midplatform
  labels:
    app: rabbitmq
spec:
  selector:
    app: rabbitmq
  type: NodePort
  ports:
    - port: 5672
      name: web
      targetPort: 5672
      protocol: TCP
    - name: amqp
      port: 15672
      targetPort: 15672
      protocol: TCP
