---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consul
  namespace: midplatform
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storage
