---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul-client
  namespace: midplatform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul-client
  template:
    metadata:
      labels:
        app: consul-client
    spec:
      containers:
        - name: consul-client
          image: hashicorp/consul:latest
          imagePullPolicy: IfNotPresent
          args:
            - agent
            - "-node=mes-client"
            - "-bind=0.0.0.0"
            - "-client=0.0.0.0"
            - "-datacenter=mes_datacenter"
            - "-retry-join=consul-server"
          ports:
            - containerPort: 8500
              name: web
              protocol: TCP
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
            requests:
              cpu: "1"
              memory: 1Gi
          livenessProbe:
            tcpSocket:
              port: 8500
            initialDelaySeconds: 30
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            tcpSocket:
              port: 8500
            initialDelaySeconds: 30
          volumeMounts:
            - mountPath: /consul/data
              name: consul
              subPath: agent
            - mountPath: /etc/localtime
              name: localtime
      volumes:
        - name: consul
          persistentVolumeClaim:
            claimName: consul
        - hostPath:
            path: /etc/localtime
            type: ""
          name: localtime
---
apiVersion: v1
kind: Service
metadata:
  name: consul-client
  namespace: midplatform
  labels:
    app: consul-client
spec:
  selector:
    app: consul-client
  type: NodePort
  ports:
    - port: 8500
      name: web
      targetPort: 8500
      protocol: TCP
