---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: devops
  annotations:
    prometheus.io/jvm: "true"
    prometheus.io/port: "9999"
  labels:
    app: jenkins
spec:
  selector:
    app: jenkins
  type: ClusterIP
  ports:
    - port: 8080
      name: web
      targetPort: 8080
      protocol: TCP
    - name: agent
      port: 50000
      targetPort: 50000
      protocol: TCP
    - name: jmx
      port: 9999
      targetPort: 9999
      protocol: TCP
