apiVersion: v1
kind: Service
metadata:
  labels:
    app: frps
  name: frps
  namespace: devops
spec:
  ports:
  - name: server
    port: 7000
    protocol: TCP
    targetPort: 7000
  - name: manage
    port: 7500
    protocol: TCP
    targetPort: 7500
  selector:
    app: frps
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frps
  namespace: devops
  labels:
    app: frps
spec:
  ingressClassName: nginx
  rules:
  - host: frps.github.icu
    http:
      paths:
      - backend:
          service:
            name: frps
            port:
              number: 7500
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - frps.github.icu
    secretName: github-tls
