---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: confluence
  namespace: devops
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: moosefs-storage

