FROM atlassian/confluence-server:8.5.2

COPY mysql-connector-java-8.0.22.jar /opt/atlassian/confluence/confluence/WEB-INF/lib/mysql-connector-java-8.0.22.jar
COPY atlassian-agent.jar /var/atlassian/atlassian-agent.jar
