apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
data:
  grafana.ini: |
    [paths]
    [server]
    root_url = https://grafana.github.icu
    [database]
    type = mysql
    host = mysql.github.icu:3306
    name = grafana
    user = grafana
    password = grafana
    [datasources]
    [remote_cache]
    [dataproxy]
    [analytics]
    [security]
    allow_embedding = true
    [security.encryption]
    [snapshots]
    [dashboards]
    [users]
    default_language = zh-Hans
    [auth]
    [auth.anonymous]
    enabled = true
    org_name = github.icu
    org_role = Viewer
    [auth.github]
    [auth.gitlab]
    [auth.google]
    [auth.grafana_com]
    [auth.azuread]
    [auth.okta]
    [auth.generic_oauth]
    [auth.basic]
    [auth.proxy]
    [auth.jwt]
    [auth.ldap]
    enabled = true
    config_file = /etc/grafana/ldap.toml
    allow_sign_up = true
    [aws]
    [azure]
    [smtp]
    [emails]
    [log]
    [log.console]
    [log.file]
    [log.syslog]
    [log.frontend]
    [quota]
    [unified_alerting]
    [alerting]
    [annotations]
    [annotations.dashboard]
    [annotations.api]
    [explore]
    [help]
    [profile]
    [query_history]
    [metrics]
    [metrics.environment_info]
    [metrics.graphite]
    [grafana_com]
    [tracing.jaeger]
    [tracing.opentelemetry.jaeger]
    [external_image_storage]
    [external_image_storage.s3]
    [external_image_storage.webdav]
    [external_image_storage.gcs]
    [external_image_storage.azure_blob]
    [external_image_storage.local]
    [rendering]
    server_url = http://grafana:8081/render
    callback_url = http://grafana:3000/
    [panels]
    [plugins]
    allow_loading_unsigned_plugins = kindlingproject-topology-panel
    [live]
    [plugin.grafana-image-renderer]
    rendering_timezone = Asia/Shanghai
    rendering_language = zh
    [enterprise]
    [feature_toggles]
    [date_formats]
    [expressions]
    [geomap]
    [white_labeling]
    [usage_insights.export]
    [usage_insights.export.storage.loki]
    [reporting]
    [analytics.summaries]
    [analytics.views]
    [auditing]
    [auditing.logs.file]
    [auditing.logs.loki]
    [auth.saml]
    [keystore.vault]
    [auth.security]
    [security.egress]
    [security.encryption]
    [security.encryption.awskms.v1]
    [security.encryption.azurekv.v1]
    [security.encryption.googlekms.v1]
    [security.encryption.hashicorpvault.v1]
    [caching]
    [caching.encryption]
    [caching.memory]
    [caching.redis]
    [caching.memcached]
    [feature_highlights]
    enabled = true
  ldap.toml: |
    [[servers]]
    host = "ad.github.icu"
    port = 389
    use_ssl = false
    start_tls = false
    ssl_skip_verify = false

    bind_dn = "cn=public,ou=users,dc=github,dc=icu"
    bind_password = '123456'

    search_filter = "(sAMAccountName=%s)"

    search_base_dns = ["dc=github,dc=icu"]

    group_search_filter = "(&(objectClass=person)(sAMAccountName=%s))"
    group_search_base_dns = ["dc=github,dc=icu"]
    group_search_filter_user_attribute = "sAMAccountName"

    [servers.attributes]
    name = "sAMAccountName"
    surname = "sn"
    username = "sAMAccountName"
    member_of = "memberOf"
    email =  "mail"

    [[servers.group_mappings]]
    group_dn = "CN=U_SA,OU=Security Groups,DC=github,DC=icu"
    org_role = "Admin"
    grafana_admin = true
    org_id = 1

    [[servers.group_mappings]]
    group_dn = ""
    org_role = "Editor"

    [[servers.group_mappings]]
    group_dn = "*"
    org_role = "Viewer"
