---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: victoria
  namespace: monitoring
spec:
  resources:
    requests:
      storage: 50Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storage

