apiVersion: v1
kind: Service
metadata:
  name: nacos
  namespace: midplatform
spec:
  ports:
  - name: http
    port: 8848
    protocol: TCP
    targetPort: 8848
  - name: client-rpc
    port: 9848
    protocol: TCP
    targetPort: 9848
  - name: raft-rpc
    port: 9849
    protocol: TCP
    targetPort: 9849
  - name: old-raft-rpc
    port: 7848
    protocol: TCP
    targetPort: 7848
  selector:
    app.kubernetes.io/instance: nacos
    app.kubernetes.io/name: nacos
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nacos
  namespace: midplatform
  labels:
    app.kubernetes.io/instance: nacos
    app.kubernetes.io/name: nacos
spec:
  ingressClassName: nginx
  rules:
  - host: nacos.github.icu
    http:
      paths:
      - backend:
          service:
            name: nacos
            port:
              number: 8848
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - nacos.github.icu
    secretName: github-tls
