apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nacos
  namespace: midplatform
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: nacos
      app.kubernetes.io/name: nacos
  replicas: 3
  serviceName: nacos-hs
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: nacos
        app.kubernetes.io/name: nacos
    spec:
      containers:
      - env:
        - name: NACOS_SERVER_PORT
          value: "8848"
        - name: NACOS_APPLICATION_PORT
          value: "8848"
        - name: PREFER_HOST_MODE
          value: hostname
        - name: SERVICE_NAME
          value: nacos-hs
        - name: DOMAIN_NAME
          value: cluster.local
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: SPRING_DATASOURCE_PLATFORM
          value: mysql
        - name: MYSQL_DATABASE_NUM
          value: "1"
        - name: MYSQL_SERVICE_HOST
          valueFrom:
            configMapKeyRef:
              key: mysql.db.host
              name: nacos-conf
        - name: MYSQL_SERVICE_DB_NAME
          valueFrom:
            configMapKeyRef:
              key: mysql.db.name
              name: nacos-conf
        - name: MYSQL_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              key: mysql.port
              name: nacos-conf
        - name: MYSQL_SERVICE_USER
          valueFrom:
            configMapKeyRef:
              key: mysql.user
              name: nacos-conf
        - name: MYSQL_SERVICE_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: mysql.password
              name: nacos-conf
        - name: MYSQL_SERVICE_DB_PARAM
          valueFrom:
            configMapKeyRef:
              key: mysql.param
              name: nacos-conf
        image: nacos/nacos-server:v2.0.3
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /nacos/v1/console/health/liveness
            port: 8848
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 10
        name: nacos
        ports:
        - containerPort: 8848
          name: http
          protocol: TCP
        - containerPort: 9848
          name: client-rpc
          protocol: TCP
        - containerPort: 9849
          name: raft-rpc
          protocol: TCP
        - containerPort: 7848
          name: old-raft-rpc
          protocol: TCP
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
        startupProbe:
          failureThreshold: 3
          httpGet:
            path: /nacos/v1/console/health/readiness
            port: 8848
            scheme: HTTP
          initialDelaySeconds: 180
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 10
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
        - mountPath: /home/nacos/plugins/peer-finder
          name: data
          subPath: nacos/plugins/peer-finder
        - mountPath: /home/nacos/data
          name: data
          subPath: nacos/data
        - mountPath: /home/nacos/logs
          name: data
          subPath: nacos/logs
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
            type: ""
      initContainers:
      - image: nacos/nacos-peer-finder-plugin:1.1
        imagePullPolicy: IfNotPresent
        name: peer-finder-plugin-install
        volumeMounts:
        - mountPath: /home/nacos/plugins/peer-finder
          name: data
          subPath: nacos/plugins/peer-finder
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
      storageClassName: moosefs-storage
      volumeMode: Filesystem
