---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cmdb
  namespace: veops
spec:
  resources:
    requests:
      storage: 50Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storage
