apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ntp-exporter
  name: ntp-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ntp-exporter
  template:
    metadata:
      labels:
        app: ntp-exporter
    spec:
      containers:
      - image: ghcr.io/sapcc/ntp_exporter:latest
        args:
          - -ntp.source=http
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 9559
          timeoutSeconds: 3
        name: ntp-exporter
        ports:
        - containerPort: 9559
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 9559
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 256Mi
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - mountPath: /etc/localtime
          name: localtime
      volumes:
      - hostPath:
          path: /etc/localtime
          type: ""
        name: localtime
