apiVersion: v1
kind: Service
metadata:
  labels:
    app: ntp-exporter
  name: ntp-exporter
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 9559
    protocol: TCP
    targetPort: 9559
  selector:
    app: ntp-exporter
  type: ClusterIP
