apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: midplatform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - env:
        - name: ELASTICSEARCH_HOSTS
          value: http://elasticsearch-hs:9200
        - name: ELASTICSEARCH_USERNAME
          value: elastic
        - name: ELASTICSEARCH_PASSWORD
          value: elastic
        image: kibana:7.17.5
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 5601
          timeoutSeconds: 1
        name: kibana
        ports:
        - containerPort: 5601
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 5601
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 512Mi
        startupProbe:
          failureThreshold: 20
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 5601
        volumeMounts:
        - mountPath: /etc/localtime
          name: localtime
      volumes:
      - hostPath:
          path: /etc/localtime
          type: ""
        name: localtime
