apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: midplatform
  labels:
    app: kibana
spec:
  ports:
  - name: http
    port: 5601
    protocol: TCP
    targetPort: 5601
  selector:
    app: kibana
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana
  namespace: midplatform
  labels:
    app: kibana
spec:
  ingressClassName: nginx
  rules:
  - host: kibana.github.icu
    http:
      paths:
      - backend:
          service:
            name: kibana
            port:
              number: 5601
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - kibana.github.icu
    secretName: github-tls
