---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skywalking-ui
  namespace: midplatform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skywalking-ui
  template:
    metadata:
      labels:
        app: skywalking-ui
    spec:
      containers:
        - name: skywalking-ui
          env:
          - name: SW_OAP_ADDRESS
            value: "http://skywalking-oap:12800" #设置读取oap的端口
          - name: TZ
            value: Asia/Shanghai
          image: apache/skywalking-ui:10.1.0
          securityContext:
            runAsUser: 0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 3
          readinessProbe:
            tcpSocket:
              port: 8080
            failureThreshold: 5
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          ports:
            - containerPort: 8080
              name: skywalking-ui
              protocol: TCP
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
            requests:
              cpu: "1"
              memory: 1Gi
          volumeMounts:
            - mountPath: /etc/localtime
              name: localtime
      volumes:
        - hostPath:
            path: /etc/localtime
            type: ""
          name: localtime
---
apiVersion: v1
kind: Service
metadata:
  name: skywalking-ui
  namespace: midplatform
spec:
  selector:
    app: skywalking-ui
  type: NodePort
  ports:
    - name: skywalking-ui
      port: 8080
      protocol: TCP
      targetPort: 8080
