---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alerta
  namespace: monitoring
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: moosefs-storage

