---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea
  namespace: gitea
spec:
  resources:
    requests:
      storage: 100Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storage
