---
apiVersion: v1
kind: Service
metadata:
  name: gitea
  namespace: gitea
  labels:
    app: gitea
spec:
  selector:
    app: gitea
  type: NodePort
  ports:
    - port: 3000
      name: web
      targetPort: 3000
      protocol: TCP
    - port: 22
      name: ssh
      targetPort: 22
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitea
  namespace: gitea
  labels:
    app: gitea
spec:
  ingressClassName: nginx
  rules:
  - host: git.github.icu
    http:
      paths:
      - backend:
          service:
            name: gitea
            port:
              number: 3000
        path: /
        pathType: Prefix
