---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus3
  namespace: devops
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storage

