{{- if .Values.kubedoor.master.enable }}
{{- if eq .Values.tsdb.type "KubeDoor" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: victoria-metrics
  namespace: kubedoor
spec:
  selector:
    matchLabels:
      app: victoria-metrics
  template:
    metadata:
      labels:
        app: victoria-metrics
    spec:
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: kubedoor-victoriametrics-data
      containers:
        - name: vm
          image: registry.cn-shenzhen.aliyuncs.com/starsl/victoria-metrics:stable
          imagePullPolicy: IfNotPresent
          args:
            - -storageDataPath=/var/lib/victoria-metrics-data
            - -retentionPeriod={{ .Values.monit.vm_single.retention }}
            - -httpAuth.username={{ .Values.monit.vm_single.user }}
            - -httpAuth.password={{ .Values.monit.vm_single.passwd }}
            - -search.maxQueryLen=655350
          ports:
            - containerPort: 8428
              name: http
          volumeMounts:
            - mountPath: /var/lib/victoria-metrics-data
              name: storage
          env:
            - name: TZ
              value: Asia/Shanghai
          resources:
            limits:
              cpu: '4'
              memory: 8Gi
            requests:
              cpu: 150m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: victoria-metrics
  namespace: kubedoor
spec:
  ports:
    - port: 8428
  type: NodePort
  selector:
    app: victoria-metrics
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubedoor-victoriametrics-data
  namespace: kubedoor
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.monit.vm_single.storage }}
  storageClassName: {{ .Values.monit.vm_single.storageClass }}
{{- end }}
{{- end }}
