---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fastgpt
  namespace: gpt
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storage
