---
apiVersion: v1
data:
  mongod.conf: |-
    storage:
      dbPath: /var/lib/mongodb
      directoryPerDB: true
      journal:
        enabled: true
    processManagement:
      fork: false
      pidFilePath: /var/run/mongodb.pid
      timeZoneInfo: /usr/share/zoneinfo
    systemLog:
      destination: file
      logAppend: true
      path: /var/log/mongodb/mongodb.log
    net:
      port: 27017
      bindIp: 0.0.0.0
    security:
      authorization: enabled
      keyFile: /etc/mongodb-keyfile
    replication:
      replSetName: cluster
kind: ConfigMap
metadata:
  name: mongodb-conf
  namespace: database
