---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: database
spec:
  selector:
    app: mongodb
  type: ClusterIP
  ports:
    - name: mongodb
      port: 27017
      protocol: TCP
      targetPort: 27017
