---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: database
spec:
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  serviceName: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-node-01
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - mongodb
            topologyKey: kubernetes.io/hostname
      containers:
      - command:
        - mongod
        - -f
        - /etc/mongod.conf
        - --bind_ip_all
        image: mongo:5.0.3
        imagePullPolicy: IfNotPresent
        name: mongodb
        ports:
        - containerPort: 27017
          protocol: TCP
        resources:
          limits:
            cpu: 2000m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 0.5Gi
        volumeMounts:
          - name: localtime
            mountPath: /etc/localtime
          - name: mongodb-conf
            mountPath: /etc/mongod.conf
            subPath: mongod.conf
          - name: mongodb
            mountPath: /var/lib/mongodb
            subPath: mongodb/data
          - name: mongodb
            mountPath: /var/log/mongodb
            subPath: mongodb/logs
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
            type: ""
        - name: mongodb-conf
          configMap:
            defaultMode: 420
            name: mongodb-conf
            items:
            - key: mongod.conf
              path: mongod.conf
        - name: mongodb
          persistentVolumeClaim:
            claimName: mongodb
