---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab
  namespace: gitlab
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: moosefs-storage
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab
  namespace: gitlab
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  - name: ssh
    port: 22
    targetPort: 22
    protocol: TCP
  selector:
    app: gitlab
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  namespace: gitlab
  labels:
    app: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
      - name: gitlab
        image: gitlab/gitlab-ce:latest
        ports:
          - containerPort: 80
            name: http
            protocol: TCP
          - containerPort: 443
            name: https
            protocol: TCP
          - containerPort: 22
            name: ssh
            protocol: TCP
#        livenessProbe:
#          httpGet:
#            path: /
#            port: 80
#            scheme: HTTP
#          initialDelaySeconds: 300
#          timeoutSeconds: 5
#          periodSeconds: 10
#          successThreshold: 1
#          failureThreshold: 3
#        readinessProbe:
#          httpGet:
#            path: /
#            port: 80
#            scheme: HTTP
#          initialDelaySeconds: 5
#          timeoutSeconds: 30
#          periodSeconds: 10
#          successThreshold: 1
#          failureThreshold: 3
        volumeMounts:
          - name: gitlab
            subPath: data
            mountPath: /var/opt/gitlab
          - name: gitlab
            subPath: log
            mountPath: /var/log/gitlab
          - name: gitlab
            subPath: config
            mountPath: /etc/gitlab
          - mountPath: /etc/localtime
            name: localtime
      volumes:
        - name: gitlab
          persistentVolumeClaim:
            claimName: gitlab
        - hostPath:
            path: /etc/localtime
            type: ""
          name: localtime
