apiVersion: v1
kind: Service
metadata:
  labels:
    app: consul-exporter
  name: consul-exporter
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 9107
    protocol: TCP
    targetPort: 9107
  selector:
    app: consul-exporter
  type: ClusterIP
