---
apiVersion: v1
kind: Service
metadata:
  name: confluence
  namespace: atlassian
  labels:
    app: confluence
spec:
  selector:
    app: confluence
  type: ClusterIP
  ports:
    - port: 8090
      name: web
      targetPort: 8090
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: confluence
  namespace: atlassian
  labels:
    app: confluence
spec:
  ingressClassName: nginx
  rules:
  - host: confluence.github.icu
    http:
      paths:
      - backend:
          service:
            name: confluence
            port:
              number: 8090
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - confluence.github.icu
    secretName: github-tls
