apiVersion: v1
data:
  consul.hcl: |
    log_level = "ERROR"
    data_dir = "/consul/data"
    client_addr = "0.0.0.0"
    ui_config{
      enabled = true
    }
    server = true
    bootstrap = true
    acl = {
      enabled = true
      default_policy = "deny"
      enable_token_persistence = true
    }
kind: ConfigMap
metadata:
  name: consul-config
  namespace: monitoring
