---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consul
  namespace: monitoring
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: moosefs-storage
