---
apiVersion: v1
kind: Service
metadata:
  name: consul-cs
  namespace: monitoring
  labels:
    app: consul
spec:
  sessionAffinity: ClientIP
  selector:
    app: consul
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8500
      targetPort: 8500
---
apiVersion: v1
kind: Service
metadata:
  name: consul-hs
  namespace: monitoring
  labels:
    app: consul
spec:
  sessionAffinity: ClientIP
  selector:
    app: consul
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      protocol: TCP
      port: 8500
      targetPort: 8500
