---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich
  namespace: immich
spec:
  resources:
    requests:
      storage: 50Gi
  accessModes:
    - ReadWriteMany
  storageClassName: moosefs-storage

