---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-machine-learning
  namespace: immich
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-machine-learning
  template:
    metadata:
      labels:
        app: immich-machine-learning
    spec:
      containers:
        - name: immich-machine-learning
          env:
          - name: UPLOAD_LOCATION
            value: "./library"
          - name: DB_DATA_LOCATION
            value: "./postgres"
          - name: IMMICH_VERSION
            value: release
          - name: DB_PASSWORD
            value: postgres
          - name: DB_USERNAME
            value: postgres
          - name: DB_DATABASE_NAME
            value: immich
          image: ghcr.io/immich-app/immich-machine-learning:release
          securityContext:
            runAsUser: 0
          imagePullPolicy: IfNotPresent
          tty: true
          resources:
            limits:
              cpu: "0.5"
              memory: 1Gi
            requests:
              cpu: "0.25"
              memory: 0.5Gi
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 30
            successThreshold: 1
            tcpSocket:
              port: 3003
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 30
            successThreshold: 1
            tcpSocket:
              port: 3003
            timeoutSeconds: 5
          ports:
            - containerPort: 3003
              protocol: TCP
          volumeMounts:
            - mountPath: /cache
              name: immich
              subPath: cache
            - mountPath: /etc/localtime
              name: localtime
      volumes:
        - name: immich
          persistentVolumeClaim:
            claimName: immich
        - hostPath:
            path: /etc/localtime
            type: ""
          name: localtime
---
apiVersion: v1
kind: Service
metadata:
  name: immich-machine-learning
  namespace: immich
spec:
  ports:
    - name: immich-machine-learning
      protocol: TCP
      port: 3003
      targetPort: 3003
  type: ClusterIP
  selector:
    app: immich-machine-learning
