apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres-exporter
  name: postgres-exporter
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 9187
    protocol: TCP
    targetPort: 9187
  selector:
    app: postgres-exporter
  type: ClusterIP
