---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jms
  namespace: jms
spec:
  resources:
    requests:
      storage: 50Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storage

