---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: core
  namespace: jms
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: moosefs-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: core
  namespace: jms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core
  template:
    metadata:
      labels:
        app: core
    spec:
      containers:
        - name: core
          env:
            - name: SECRET_KEY
              value: 0imoXuphwWKE6b5JuJrJTNjvD9uGhw4sRrbW6TXddPOiX8bmnw
            - name: BOOTSTRAP_TOKEN
              value: X3uaAUpf6x83QMcn
            - name: DEBUG
              value: "FALSE"
            - name: LOG_LEVEL
              value: "ERROR"
            - name: DB_HOST
              value: mysql.jms.svc
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              value: "123456"
            - name: DB_NAME
              value: jumpserver
            - name: REDIS_HOST
              value: redis.jms.svc
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: "123456"
          image: jumpserver/core:v2.28.10
          tty: true
          command: ["/bin/bash","-c","/opt/jumpserver/entrypoint.sh","start","web"]
          securityContext:
            runAsUser: 0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 3
          readinessProbe:
            failureThreshold: 5
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            httpGet:
              port: 8080
              path: /api/health/
            timeoutSeconds: 3
          ports:
            - containerPort: 8080
              name: core-1
              protocol: TCP
            - containerPort: 8070
              name: core-2
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: "0.5"
              memory: 512Mi
          volumeMounts:
            - mountPath: /opt/jumpserver/data
              name: core
              subPath: data
            - mountPath: /opt/jumpserver/logs
              name: core
              subPath: logs
            - mountPath: /etc/localtime
              name: localtime
      volumes:
        - name: core
          persistentVolumeClaim:
            claimName: core
        - hostPath:
            path: /etc/localtime
            type: ""
          name: localtime
