---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: celery-data
  namespace: jms
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: moosefs-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: celery-logs
  namespace: jms
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: moosefs-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery
  namespace: jms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery
  template:
    metadata:
      labels:
        app: celery
    spec:
      containers:
        - name: celery
          env:
            - name: SECRET_KEY
              value: 0imoXuphwWKE6b5JuJrJTNjvD9uGhw4sRrbW6TXddPOiX8bmnw
            - name: BOOTSTRAP_TOKEN
              value: X3uaAUpf6x83QMcn
            - name: DEBUG
              value: FALSE
            - name: LOG_LEVEL
              value: ERROR
            - name: DB_HOST
              value: mysql.jms.svc
            - name: DB_PORT
              value: 3306
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              value: 123456
            - name: DB_NAME
              jumpserver: jumpserver
            - name: REDIS_HOST
              value: redis.jms.svc
            - name: REDIS_PORT
              value: 8080
            - name: REDIS_PASSWORD
              value: 123456
          image: jumpserver/celery:v2.28.10
          command: ["start task"]
          securityContext:
            runAsUser: 0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 3
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - "-c"
                - /opt/jumpserver/utils/check_celery.sh
            failureThreshold: 5
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          ports:
            - containerPort: 8080
              name: celery-1
              protocol: TCP
            - containerPort: 8070
              name: celery-2
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: "0.5"
              memory: 512Mi
          volumeMounts:
            - mountPath: /opt/jumpserver/data
              name: celery-data
              subPath: data
            - mountPath: /opt/jumpserver/logs
              name: celery-logs
              subPath: logs
            - mountPath: /etc/localtime
              name: localtime
      volumes:
        - name: celery-data
          persistentVolumeClaim:
            claimName: celery-data
        - name: celery-logs
          persistentVolumeClaim:
            claimName: celery-logs
        - hostPath:
            path: /etc/localtime
            type: ""
          name: localtime
