---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery
  namespace: jms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery
  template:
    metadata:
      labels:
        app: celery
    spec:
      containers:
        - name: celery
          env:
            - name: SECRET_KEY
              value: 0imoXuphwWKE6b5JuJrJTNjvD9uGhw4sRrbW6TXddPOiX8bmnw
            - name: BOOTSTRAP_TOKEN
              value: X3uaAUpf6x83QMcn
            - name: DEBUG
              value: "FALSE"
            - name: LOG_LEVEL
              value: "ERROR"
            - name: DB_HOST
              value: mysql
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              value: "123456"
            - name: DB_NAME
              value: jumpserver
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: "123456"
          image: jumpserver/core:v2.28.21
          args:
            - start
            - task
          securityContext:
            runAsUser: 0
          imagePullPolicy: IfNotPresent
          tty: true
#          livenessProbe:
#            exec:
#              command:
#                - /bin/bash
#                - "-c"
#                - /opt/jumpserver/utils/check_celery.sh
#            failureThreshold: 5
#            initialDelaySeconds: 30
#            periodSeconds: 5
#            successThreshold: 1
#            timeoutSeconds: 3
#          readinessProbe:
#            exec:
#              command:
#                - /bin/bash
#                - "-c"
#                - /opt/jumpserver/utils/check_celery.sh
#            failureThreshold: 5
#            initialDelaySeconds: 10
#            periodSeconds: 5
#            successThreshold: 1
#            timeoutSeconds: 3
          resources:
            limits:
              cpu: "0.5"
              memory: 1Gi
            requests:
              cpu: "0.25"
              memory: 0.5Gi
          volumeMounts:
            - mountPath: /opt/jumpserver/data
              name: jms
              subPath: core/data
            - mountPath: /opt/jumpserver/logs
              name: jms
              subPath: core/logs
            - mountPath: /etc/localtime
              name: localtime
      volumes:
        - name: jms
          persistentVolumeClaim:
            claimName: jms
        - hostPath:
            path: /etc/localtime
            type: ""
          name: localtime
