---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lion
  namespace: jms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lion
  template:
    metadata:
      labels:
        app: lion
    spec:
      containers:
        - name: lion
          env:
            - name: CORE_HOST
              value: http://core:8080
            - name: BOOTSTRAP_TOKEN
              value: X3uaAUpf6x83QMcn
            - name: LOG_LEVEL
              value: "ERROR"
          image: jumpserver/lion:v2.28.21
          tty: true
          securityContext:
            runAsUser: 0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 8081
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              port: 8081
              path: /lion/health/
            failureThreshold: 5
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: "0.5"
              memory: 512Mi
          volumeMounts:
            - mountPath: /opt/lion/data
              name: jms
              subPath: lion/data
            - mountPath: /etc/localtime
              name: localtime
      volumes:
        - name: jms
          persistentVolumeClaim:
            claimName: jms
        - hostPath:
            path: /etc/localtime
            type: ""
          name: localtime
---
apiVersion: v1
kind: Service
metadata:
  name: lion
  namespace: jms
spec:
  ports:
    - name: lion
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
  selector:
    app: lion
