---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: jms
spec:
  type: NodePort
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: jms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          env:
            - name: CORE_HOST
              value: http://core:8080
            - name: BOOTSTRAP_TOKEN
              value: X3uaAUpf6x83QMcn
            - name: LOG_LEVEL
              value: "ERROR"
          image: jumpserver/web:v2.28.15
          tty: true
          securityContext:
            runAsUser: 0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 80
            timeoutSeconds: 3
          readinessProbe:
            failureThreshold: 5
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            httpGet:
              port: 80
              path: /
            timeoutSeconds: 3
          ports:
            - containerPort: 80
              name: web
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: "0.5"
              memory: 512Mi
          volumeMounts:
            - mountPath: /opt/jumpserver/data
              name: jms
              subPath: core/data
            - mountPath: /var/log/nginx
              name: jms
              subPath: web/log
            - mountPath: /etc/localtime
              name: localtime
      volumes:
        - name: jms
          persistentVolumeClaim:
            claimName: jms
        - hostPath:
            path: /etc/localtime
            type: ""
          name: localtime
