---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-log
  namespace: jms
spec:
  resources:
    requests:
      storage: 5Mi
  accessModes:
    - ReadWriteMany
  storageClassName: moosefs-storage
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: jms
spec:
  type: NodePort
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: jms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          env:
            - name: CORE_HOST
              value: http://core.jms.svc:8080
            - name: BOOTSTRAP_TOKEN
              value: X3uaAUpf6x83QMcn
            - name: LOG_LEVEL
              value: ERROR
          image: jumpserver/web:v2.28.10
          securityContext:
            runAsUser: 0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 80
            timeoutSeconds: 3
          readinessProbe:
            failureThreshold: 5
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 80
            timeoutSeconds: 3
          ports:
            - containerPort: 80
              name: web
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: "0.5"
              memory: 512Mi
          volumeMounts:
            - mountPath: /var/log/nginx
              name: web-log
              subPath: log
            - mountPath: /etc/localtime
              name: localtime
      volumes:
        - name: web-log
          persistentVolumeClaim:
            claimName: web-log
        - hostPath:
            path: /etc/localtime
            type: ""
          name: localtime
