{
 "title": "K8S每日高峰时段资源数据分析",
 "tags": [ "StarsL.cn" ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "table", "label": "数据表", "query": "show tables from kubedoor" },
   {
    "name": "env",
    "label": "环境",
    "query": "SELECT\nconcat(env ,'#env = \\'',env,'\\'') \nfrom  kubedoor.${table} PREWHERE $__timeFilter(date) \ngroup by env"
   },
   {
    "name": "namespace",
    "label": "命名空间",
    "query": "SELECT\nconcat(namespace,'#namespace = \\'',namespace,'\\'') \nfrom  kubedoor.${table} PREWHERE $__timeFilter(date) and ${env}\ngroup by namespace"
   },
   {
    "name": "deployment",
    "label": "微服务",
    "query": "SELECT\nconcat(deployment,'#deployment = \\'',deployment,'\\'') \nfrom  kubedoor.${table} PREWHERE $__timeFilter(date) and ${env} and ${namespace}\ngroup by deployment"
   },
   {
    "name": "maxday",
    "label": "最大资源使用的日期",
    "query": "SELECT\n\nconcat(formatDateTime(toDateTime(date), '%Y-%m-%d'),'#',formatDateTime(toDateTime(date), '%Y-%m-%d %T'))\n AS formatted_date\nFROM\n    kubedoor.${table}\nPREWHERE\n    $__timeFilter(date) AND ${env}\nGROUP BY\n    formatted_date\nORDER BY\n    SUM(pod_count * p95_pod_load) DESC\nLIMIT\n    1\n"
   }
  ]
 },
 "panels": [
  {
   "title": "【${__from:date:YYYY-MM-DD}~${__to:date:YYYY-MM-DD}最大资源使用的日期：${maxday}】【$env】高峰时段全局资源统计与各资源TOP10",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(DISTINCT namespace) as \"命名空间\"\r\n  FROM\r\n    kubedoor.${table} PREWHERE date = '${maxday}'AND ${env}\r\n\r\n"
    },
    {
     "rawSql": "select count(DISTINCT deployment) as \"微服务\"\r\n  FROM\r\n    kubedoor.${table} PREWHERE date = '${maxday}'AND ${env}\r\n\r\n"
    },
    {
     "rawSql": "select sum(pod_count) as \"Pod\"\r\n  FROM\r\n    kubedoor.${table} PREWHERE date = '${maxday}'AND ${env}\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(request_pod_cpu_m * pod_count)/1000 as \"CPU需求\"\r\n  FROM\r\n    kubedoor.${table} PREWHERE date = '${maxday}'AND ${env}\r\n\r\n"
    },
    {
     "rawSql": "select sum(p95_pod_load * pod_count) as \"负载使用\"\r\n  FROM\r\n    kubedoor.${table} PREWHERE date = '${maxday}'AND ${env}\r\n\r\n"
    },
    {
     "rawSql": "select sum(limit_pod_cpu_m * pod_count)/1000 as \"CPU限制\"\r\n  FROM\r\n    kubedoor.${table} PREWHERE date = '${maxday}'AND ${env}\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(request_pod_mem_mb * pod_count) as \"内存需求\"\r\n  FROM\r\n    kubedoor.${table} PREWHERE date = '${maxday}'AND ${env}\r\n\r\n"
    },
    {
     "rawSql": "select sum(p95_pod_wss_mb * pod_count) as \"内存使用\"\r\n  FROM\r\n    kubedoor.${table} PREWHERE date = '${maxday}'AND ${env}\r\n\r\n"
    },
    {
     "rawSql": "select sum(limit_pod_mem_mb * pod_count) as \"内存限制\"\r\n  FROM\r\n    kubedoor.${table} PREWHERE date = '${maxday}'AND ${env}\r\n\r\n"
    }
   ]
  },
  {
   "title": "微服务负载使用TOP10",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "  SELECT\r\n    concat(namespace,':',deployment) AS name,\r\n    sum(p95_pod_load * pod_count) AS load\r\n  FROM\r\n    kubedoor.${table} PREWHERE date = '${maxday}'AND ${env}\r\n  GROUP BY\r\n    name\r\n    order by load desc\r\n    limit 10"
    }
   ]
  },
  {
   "title": "微服务CPU使用率TOP10",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 5, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "  SELECT\r\n    concat(namespace,':',deployment) AS name,\r\n    sum(p95_pod_cpu_pct) AS load\r\n  FROM\r\n    kubedoor.${table} PREWHERE date = '${maxday}'AND ${env}\r\n  GROUP BY\r\n    name\r\n    order by load desc\r\n    limit 10"
    }
   ]
  },
  {
   "title": "微服务内存使用TOP10",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 5, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "  SELECT\r\n    concat(namespace,':',deployment) AS name,\r\n    sum(p95_pod_wss_mb * pod_count) AS load\r\n  FROM\r\n    kubedoor.${table} PREWHERE date = '${maxday}'AND ${env}\r\n  GROUP BY\r\n    name\r\n    order by load desc\r\n    limit 10"
    }
   ]
  },
  {
   "title": "微服务内存使用率TOP10",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 5, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "  SELECT\r\n    concat(namespace,':',deployment) AS name,\r\n    sum(p95_pod_wss_pct) AS load\r\n  FROM\r\n    kubedoor.${table} PREWHERE date = '${maxday}'AND ${env}\r\n  GROUP BY\r\n    name\r\n    order by load desc\r\n    limit 10"
    }
   ]
  },
  {
   "title": "微服务Pod数TOP10",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "  SELECT\r\n    concat(namespace,':',deployment) AS name,\r\n    sum(pod_count) AS load\r\n  FROM\r\n    kubedoor.${table} PREWHERE date = '${maxday}'AND ${env}\r\n  GROUP BY\r\n    name\r\n    order by load desc\r\n    limit 10"
    }
   ]
  },
  { "title": "命名空间级别最大资源使用分析", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "【${__from:date:YYYY-MM-DD}~${__to:date:YYYY-MM-DD}最大资源使用的日期：${maxday}】【各命名空间级别】高峰时段P95资源使用量与资源占整体资源比例",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "-- 计算每个命名空间的值\r\nWITH per_namespace AS (\r\n  SELECT\r\n    namespace,\r\n    count(DISTINCT(deployment)) AS deployment,\r\n    sum(pod_count) AS pod,\r\n    sum(p95_pod_load * pod_count) AS load,\r\n    sum(p95_pod_wss_mb * pod_count) AS mem,\r\n    sum(request_pod_cpu_m * pod_count/1000) AS cpu_request,\r\n    sum(limit_pod_cpu_m * pod_count/1000) AS cpu_limit,\r\n    sum(request_pod_mem_mb * pod_count) AS mem_request,\r\n    sum(limit_pod_mem_mb * pod_count) AS mem_limit\r\n  FROM\r\n    kubedoor.${table} PREWHERE date = '${maxday}'AND ${env}\r\n  GROUP BY\r\n    namespace\r\n),\r\n-- 计算总数\r\ntotals AS (\r\n  SELECT\r\n    sum(deployment) AS total_deployment,\r\n    sum(pod) AS total_pod,\r\n    sum(load) AS total_load,\r\n    sum(mem) AS total_mem,\r\n    sum(cpu_request) AS total_cpu_request,\r\n    sum(cpu_limit) AS total_cpu_limit,\r\n    sum(mem_request) AS total_mem_request,\r\n    sum(mem_limit) AS total_mem_limit\r\n  FROM\r\n    per_namespace\r\n) -- 合并并计算占比\r\nSELECT\r\n  per_namespace.namespace,\r\n  per_namespace.deployment,\r\n  per_namespace.deployment / totals.total_deployment AS deployment_percentage,\r\n  per_namespace.pod,\r\n  per_namespace.pod / totals.total_pod AS pod_percentage,\r\n\r\n  per_namespace.cpu_request,\r\n  per_namespace.cpu_request / totals.total_cpu_request AS cpu_request_percentage,\r\n  per_namespace.load,\r\n  per_namespace.load / totals.total_load AS load_percentage,\r\n  per_namespace.cpu_limit,\r\n  per_namespace.cpu_limit / totals.total_cpu_limit AS cpu_limit_percentage,\r\n\r\n  per_namespace.mem_request,\r\n  per_namespace.mem_request / totals.total_mem_request AS mem_request_percentage,\r\n  per_namespace.mem,\r\n  per_namespace.mem / totals.total_mem AS mem_percentage,\r\n  per_namespace.mem_limit,\r\n  per_namespace.mem_limit / totals.total_mem_limit AS mem_limit_percentage\r\n\r\nFROM\r\n  per_namespace\r\n  CROSS JOIN totals"
    }
   ]
  },
  {
   "title": "微服务整体分析【$namespace】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "【${__from:date:YYYY-MM-DD}~${__to:date:YYYY-MM-DD}最大资源使用的日期：${maxday}】【各微服务级别】高峰时段P95资源使用量与资源占整体资源比例",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 79 },
     "targets": [
      {
       "rawSql": "-- 计算每个命名空间的值\r\nWITH per_namespace AS (\r\n  SELECT\r\n    namespace,\r\n    deployment,\r\n    sum(pod_count) AS pod,\r\n    sum(p95_pod_load * pod_count) AS load,\r\n    sum(p95_pod_wss_mb * pod_count) AS mem,\r\n    sum(request_pod_cpu_m * pod_count/1000) AS cpu_request,\r\n    sum(limit_pod_cpu_m * pod_count/1000) AS cpu_limit,\r\n    sum(request_pod_mem_mb * pod_count) AS mem_request,\r\n    sum(limit_pod_mem_mb * pod_count) AS mem_limit\r\n  FROM\r\n    kubedoor.${table} PREWHERE date = '${maxday}' AND ${env} AND ${namespace}\r\n  GROUP BY\r\n    namespace,deployment\r\n),\r\n-- 计算总数\r\ntotals AS (\r\n  SELECT\r\n    sum(pod) AS total_pod,\r\n    sum(load) AS total_load,\r\n    sum(mem) AS total_mem,\r\n    sum(cpu_request) AS total_cpu_request,\r\n    sum(cpu_limit) AS total_cpu_limit,\r\n    sum(mem_request) AS total_mem_request,\r\n    sum(mem_limit) AS total_mem_limit\r\n  FROM\r\n    per_namespace\r\n) -- 合并并计算占比\r\nSELECT\r\n  per_namespace.namespace,\r\n  per_namespace.deployment,\r\n  per_namespace.pod,\r\n  per_namespace.pod / totals.total_pod AS pod_percentage,\r\n  per_namespace.cpu_request,\r\n  per_namespace.cpu_request / totals.total_cpu_request AS cpu_request_percentage,\r\n  per_namespace.load,\r\n  per_namespace.load / totals.total_load AS load_percentage,\r\n  per_namespace.cpu_limit,\r\n  per_namespace.cpu_limit / totals.total_cpu_limit AS cpu_limit_percentage,\r\n\r\n  per_namespace.mem_request,\r\n  per_namespace.mem_request / totals.total_mem_request AS mem_request_percentage,\r\n  per_namespace.mem,\r\n  per_namespace.mem / totals.total_mem AS mem_percentage,\r\n  per_namespace.mem_limit,\r\n  per_namespace.mem_limit / totals.total_mem_limit AS mem_limit_percentage\r\n\r\nFROM\r\n  per_namespace\r\n  CROSS JOIN totals"
      }
     ]
    },
    {
     "title": "每日高峰时段P95CPU使用率",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "rawSql": "SELECT date as time, deployment, max(p95_pod_cpu_pct) FROM kubedoor.${table} PREWHERE $__timeFilter(date) and ${env} and ${namespace} and ${deployment}\r\ngroup by time,deployment\r\norder by time\r\n"
      }
     ]
    },
    {
     "title": "每日高峰时段P95内存使用率",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 91 },
     "targets": [
      {
       "rawSql": "SELECT date as time, deployment, max(p95_pod_wss_pct) FROM kubedoor.${table} PREWHERE $__timeFilter(date) and ${env} and ${namespace} and ${deployment}\r\ngroup by time,deployment\r\norder by time\r\n"
      }
     ]
    },
    {
     "title": "每日微服务Pod数",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 91 },
     "targets": [
      {
       "rawSql": "SELECT date as time, deployment, max(pod_count) FROM kubedoor.${table} PREWHERE $__timeFilter(date) and ${env} and ${namespace} and ${deployment}\r\ngroup by time,deployment\r\norder by time\r\n"
      }
     ]
    },
    {
     "title": "【${__from:date:YYYY-MM-DD}~${__to:date:YYYY-MM-DD}最大资源使用的日期：${maxday}】【各Pod级别】高峰时段P95资源使用量与使用率分析",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 101 },
     "targets": [
      {
       "rawSql": "-- 计算每个命名空间的值\r\nWITH per_namespace AS (\r\n  SELECT\r\n    namespace,\r\n    deployment,\r\n    sum(pod_count) AS pod,\r\n    sum(p95_pod_load) AS load,\r\n    sum(p95_pod_wss_mb) AS mem,\r\n    sum(p95_pod_cpu_pct) AS cpu_pct,\r\n    sum(p95_pod_wss_pct) AS mem_pct,\r\n    sum(request_pod_cpu_m/1000) AS cpu_request,\r\n    sum(limit_pod_cpu_m/1000) AS cpu_limit,\r\n    sum(request_pod_mem_mb) AS mem_request,\r\n    sum(limit_pod_mem_mb) AS mem_limit\r\n  FROM\r\n    kubedoor.${table} PREWHERE date = '${maxday}' AND ${env} AND ${namespace}\r\n  GROUP BY\r\n    namespace,deployment\r\n),\r\n-- 计算总数\r\ntotals AS (\r\n  SELECT\r\n    sum(pod) AS total_pod\r\n  FROM\r\n    per_namespace\r\n) -- 合并并计算占比\r\nSELECT\r\n  per_namespace.namespace,\r\n  per_namespace.deployment,\r\n  per_namespace.pod,\r\n  per_namespace.pod / totals.total_pod * 100 AS pod_percentage,\r\n\r\n  per_namespace.cpu_request,\r\n  per_namespace.load,\r\n  per_namespace.cpu_pct,\r\n  per_namespace.cpu_limit,\r\n\r\n  per_namespace.mem_request,\r\n  per_namespace.mem,\r\n  per_namespace.mem_pct,\r\n  per_namespace.mem_limit\r\n\r\nFROM\r\n  per_namespace\r\n  CROSS JOIN totals"
      }
     ]
    }
   ]
  },
  {
   "title": "微服务资源曲线图【$namespace】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "各微服务每日高峰时段P95 CPU负载",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 711 },
     "targets": [
      {
       "rawSql": "SELECT date as time, deployment, max(p95_pod_load * pod_count) FROM kubedoor.${table} PREWHERE $__timeFilter(date) and ${env} and ${namespace} and ${deployment}\r\ngroup by time,deployment\r\norder by time\r\n"
      }
     ]
    },
    {
     "title": "各微服务CPU需求值",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 711 },
     "targets": [
      {
       "rawSql": "SELECT date as time, deployment, max(request_pod_cpu_m * pod_count)/1000 FROM kubedoor.${table} PREWHERE $__timeFilter(date) and ${env} and ${namespace} and ${deployment}\r\ngroup by time,deployment\r\norder by time\r\n"
      }
     ]
    },
    {
     "title": "各微服务CPU限制值",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 711 },
     "targets": [
      {
       "rawSql": "SELECT date as time, deployment, max(limit_pod_cpu_m * pod_count)/1000 FROM kubedoor.${table} PREWHERE $__timeFilter(date) and ${env} and ${namespace} and ${deployment}\r\ngroup by time,deployment\r\norder by time\r\n"
      }
     ]
    },
    {
     "title": "各微服务每日高峰时段P95 内存使用量",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 721 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "targets": [
      {
       "rawSql": "SELECT date as time, deployment, max(p95_pod_wss_mb * pod_count) FROM kubedoor.${table} PREWHERE $__timeFilter(date) and ${env} and ${namespace} and ${deployment}\r\ngroup by time,deployment\r\norder by time\r\n"
      }
     ]
    },
    {
     "title": "各微服务内存需求值",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 721 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "targets": [
      {
       "rawSql": "SELECT date as time, deployment, max(request_pod_mem_mb * pod_count) FROM kubedoor.${table} PREWHERE $__timeFilter(date) and ${env} and ${namespace} and ${deployment}\r\ngroup by time,deployment\r\norder by time\r\n"
      }
     ]
    },
    {
     "title": "各微服务内存限制值",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 721 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "targets": [
      {
       "rawSql": "SELECT date as time, deployment, max(limit_pod_mem_mb * pod_count) FROM kubedoor.${table} PREWHERE $__timeFilter(date) and ${env} and ${namespace} and ${deployment}\r\ngroup by time,deployment\r\norder by time\r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod资源曲线图【$namespace】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "各Pod每日高峰时段P95 CPU负载",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 324 },
     "targets": [
      {
       "rawSql": "SELECT date as time, deployment, max(p95_pod_load) FROM kubedoor.${table} PREWHERE $__timeFilter(date) and ${env} and ${namespace} and ${deployment}\r\ngroup by time,deployment\r\norder by time\r\n"
      }
     ]
    },
    {
     "title": "各Pod CPU需求值",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 324 },
     "targets": [
      {
       "rawSql": "SELECT date as time, deployment, max(request_pod_cpu_m)/1000 FROM kubedoor.${table} PREWHERE $__timeFilter(date) and ${env} and ${namespace} and ${deployment}\r\ngroup by time,deployment\r\norder by time\r\n"
      }
     ]
    },
    {
     "title": "各Pod CPU限制值",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 324 },
     "targets": [
      {
       "rawSql": "SELECT date as time, deployment, max(limit_pod_cpu_m)/1000 FROM kubedoor.${table} PREWHERE $__timeFilter(date) and ${env} and ${namespace} and ${deployment}\r\ngroup by time,deployment\r\norder by time\r\n"
      }
     ]
    },
    {
     "title": "各Pod每日高峰时段P95内存使用量",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 334 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "targets": [
      {
       "rawSql": "SELECT date as time, deployment, max(p95_pod_wss_mb) FROM kubedoor.${table} PREWHERE $__timeFilter(date) and ${env} and ${namespace} and ${deployment}\r\ngroup by time,deployment\r\norder by time\r\n"
      }
     ]
    },
    {
     "title": "各Pod内存需求值",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 334 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "targets": [
      {
       "rawSql": "SELECT date as time, deployment, max(request_pod_mem_mb) FROM kubedoor.${table} PREWHERE $__timeFilter(date) and ${env} and ${namespace} and ${deployment}\r\ngroup by time,deployment\r\norder by time\r\n"
      }
     ]
    },
    {
     "title": "各Pod内存限制值",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 334 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "targets": [
      {
       "rawSql": "SELECT date as time, deployment, max(limit_pod_mem_mb) FROM kubedoor.${table} PREWHERE $__timeFilter(date) and ${env} and ${namespace} and ${deployment}\r\ngroup by time,deployment\r\norder by time\r\n"
      }
     ]
    }
   ]
  }
 ]
}