---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitwarden
  namespace: tools
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storage
