---
apiVersion: v1
kind: Service
metadata:
  name: bitwarden
  namespace: tools
  labels:
    app: bitwarden
spec:
  selector:
    app: bitwarden
  type: ClusterIP
  ports:
    - port: 80
      name: web
      targetPort: 80
      protocol: TCP
    - port: 3012
      name: websocket
      targetPort: 3012
      protocol: TCP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bitwarden
  namespace: tools
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "5000m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
  labels:
    app: bitwarden
spec:
  ingressClassName: nginx
  rules:
  - host: password.github.icu
    http:
      paths:
      - backend:
          service:
            name: bitwarden
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - bitwarden.github.icu
    secretName: github-tls
