---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitwarden
  namespace: tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitwarden
  template:
    metadata:
      labels:
        app: bitwarden
    spec:
      containers:
        - name: bitwarden
          image: vaultwarden/server:latest
          env:
            - name: WEBSOCKET_ENABLE
              value: "true"
            - name: SIGNUPS_ALLOWED
              value: "false"
            - name: DOMAIN
              value: "https://password.github.icu"
            - name: ADMIN_TOKEN
              value: "UqiLZGrPFez0SJkvUhux84IOWFayGarZQuQhG4RnetYJMiGNKJezZsLzmBCIEVYQ"
            - name: SQLITE_WAL_MODE
              value: "true"
            - name: SQLITE_CACHE_SIZE
              value: "256"
            - name: DB_MAX_CONNECTIONS
              value: "50"
            - name: DB_TIMEOUT
              value: "30"
            - name: HTTP2_ENABLED
              value: "true"
            - name: WEBSOCKET_PING_INTERVAL
              value: "60"
            - name: AESNI_ENABLED
              value: "true"
          securityContext:
            runAsUser: 0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: web
              protocol: TCP
            - containerPort: 3012
              name: websocket
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 1G
            requests:
              cpu: "0.5"
              memory: 512Mi
          livenessProbe:
            httpGet:
              port: 80
              path: /
            initialDelaySeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10
          readinessProbe:
            httpGet:
              port: 80
              path: /
            initialDelaySeconds: 10
          volumeMounts:
            - mountPath: /etc/localtime
              name: localtime
            - name: bitwarden
              mountPath: /data
              subPath: bitwarden/data
      volumes:
        - name: bitwarden
          persistentVolumeClaim:
            claimName: bitwarden
        - hostPath:
            path: /etc/localtime
            type: ""
          name: localtime
