{{- if .Values.kubedoor.agent.enable }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: kubedoor-agent-config
  namespace: kubedoor
data:
  KUBEDOOR_MASTER: {{ .Values.kubedoor.master.ws | quote }}
  PROM_K8S_TAG_VALUE: {{ .Values.tsdb.external_labels_value | quote }}
  MSG_TYPE: {{ .Values.config.MSG_TYPE | quote }}
  MSG_TOKEN: {{ .Values.config.MSG_TOKEN | quote }}
  OSS_URL: {{ .Values.config.OSS_URL | quote }}

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubedoor-agent
  namespace: kubedoor

---

apiVersion: v1
kind: Secret
metadata:
  name: kubedoor-agent
  namespace: kubedoor
  annotations:
    kubernetes.io/service-account.name: "kubedoor-agent"
type: kubernetes.io/service-account-token

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubedoor-agent-cr
rules:
  - verbs:
      - '*'
    apiGroups:
      - '*'
    resources:
      - '*'
  - verbs:
      - '*'
    nonResourceURLs:
      - '*'

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubedoor-agent-crb
subjects:
  - kind: ServiceAccount
    name: kubedoor-agent
    namespace: kubedoor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubedoor-agent-cr

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedoor-agent
  namespace: kubedoor
  labels:
    app: kubedoor-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubedoor-agent
  template:
    metadata:
      labels:
        app: kubedoor-agent
    spec:
      containers:
        - name: kubedoor-agent
          {{- if eq .Values.image.agent_build "go" }}
          image: {{ .Values.image.repository }}/kubedoor-agent:{{ .Values.image.kubedoor_agent_go_tag }}
          {{- else }}
          image: {{ .Values.image.repository }}/kubedoor-agent:{{ .Values.image.kubedoor_agent_tag }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: kubedoor-agent-config
          env:
            - name: TZ
              value: Asia/Shanghai
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 1m
              memory: 1Mi
          livenessProbe:
            httpGet:
              path: /api/health
              port: 443
              scheme: HTTPS
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/health
              port: 443
              scheme: HTTPS
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          imagePullPolicy: Always
      restartPolicy: Always
      serviceAccountName: kubedoor-agent
      serviceAccount: kubedoor-agent
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
---
apiVersion: v1
kind: Service
metadata:
  name: kubedoor-agent
  namespace: kubedoor
  labels:
    app: kubedoor-agent
spec:
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  selector:
    app: kubedoor-agent
  type: ClusterIP 
{{- end }}
