apiVersion: v1
kind: Service
metadata:
  labels:
    app: vmware-exporter
  name: vmware-exporter
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 9272
    protocol: TCP
    targetPort: 9272
  selector:
    app: vmware-exporter
  type: ClusterIP
