---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins
      containers:
        - name: jenkins
          env:
          - name: JAVA_OPTS
            value: |
              -XshowSettings:vm
              -Dhudson.slaves.NodeProvisioner.initialDelay=0
              -Dhudson.slaves.NodeProvisioner.MARGIN=50
              -Dhudson.slaves.NodeProvisioner.MARGIN0=0.85
              -Duser.timezone=Asia/Shanghai
              -Dfile.encoding=UTF-8
              -Djava.awt.headless=true
          - name: JENKINS_OPTS
            value: |
              --prefix=/
              --sessionTimeout=1440
              --sessionEviction=1440
          image: jenkins/jenkins:2.484
          securityContext:
            runAsUser: 0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: web
              protocol: TCP
            - containerPort: 50000
              name: agent
              protocol: TCP
          resources:
            limits:
              cpu: "2"
              memory: 4Gi
            requests:
              cpu: "1"
              memory: 2Gi
#          livenessProbe:
#            httpGet:
#              port: 8080
#              path: /login
#            initialDelaySeconds: 60
#            timeoutSeconds: 5
#            failureThreshold: 12
#          readinessProbe:
#            httpGet:
#              port: 8080
#              path: /login
#            initialDelaySeconds: 60
          volumeMounts:
            - mountPath: /var/jenkins_home
              name: jenkins-volume
              subPath: jenkins-home
            - mountPath: /etc/localtime
              name: localtime
      volumes:
        - name: jenkins-volume
          persistentVolumeClaim:
            claimName: jenkins
        - hostPath:
            path: /etc/localtime
            type: ""
          name: localtime
