---
apiVersion: v1
kind: Service
metadata:
  name: hesk
  namespace: tools
  labels:
    app: hesk
spec:
  selector:
    app: hesk
  type: ClusterIP
  ports:
    - port: 80
      name: web
      targetPort: 80
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hesk
  namespace: tools
  labels:
    app: hesk
spec:
  ingressClassName: nginx
  rules:
  - host: hesk.github.icu
    http:
      paths:
      - backend:
          service:
            name: hesk
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - hesk.github.icu
    secretName: github-tls
