---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-conf
  namespace: devops
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: moosefs-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-log
  namespace: devops
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: moosefs-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: devops
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 80
            timeoutSeconds: 3
          securityContext:
            runAsUser: 0
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
            - containerPort: 443
              name: https
              protocol: TCP
          readinessProbe:
            failureThreshold: 5
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 80
            timeoutSeconds: 3
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
#          volumeMounts:
#            - mountPath: /var/log/nginx
#              name: nginx-log
#            - mountPath: /etc/nginx/conf.d
#              name: nginx-conf
#            - mountPath: /etc/localtime
#              name: localtime
#      volumes:
#        - name: nginx-log
#          persistentVolumeClaim:
#            claimName: nginx-log
#        - name: nginx-conf
#          persistentVolumeClaim:
#            claimName: nginx-conf
#        - name: localtime
#          hostPath:
#            path: /etc/localtime
#            type: ""
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: devops
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
    - name: web
      protocol: TCP
      port: 80
