---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-vhost
  namespace: devops
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-log
  namespace: devops
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storage

