---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: database
  labels:
    app: clickhouse
spec:
  sessionAffinity: ClientIP
  selector:
    app: clickhouse
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8123
      targetPort: 8123
    - name: server
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: metrics
      protocol: TCP
      port: 9363
      targetPort: 9363
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clickhouse
  namespace: database
  labels:
    app: clickhouse
spec:
  ingressClassName: nginx
  rules:
  - host: clickhouse.github.icu
    http:
      paths:
      - backend:
          service:
            name: clickhouse
            port:
              number: 8123
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - clickhouse.github.icu
    secretName: github-tls
