image:
  repository: swr.cn-south-1.myhuaweicloud.com/starsl.cn
  agent_build: python # 默认kubedoor-agent是Python的版本，改为"go"可切换为@comqx(https://github.com/comqx)开发维护的go版本（也可以安装后修改镜像标签或在WEBUI-agent管理中切换版本）
  kubedoor_agent_go_tag: 1.1.3-go
  kubedoor_agent_tag: 1.1.3
  kubedoor_master_tag: 1.1.0
  kubedoor_web_tag: 1.1.1
  kubedoor_alarm_tag: 1.0.2

  grafana_plugins_init: 0.1.0 
  grafana_oss: 11.4.0

tsdb:
  type: "KubeDoor" 

kubedoor:
  agent:
    enable: false
  master:
    enable: false
  web:
    enable: false
  dash:
    enable: false
  admis:
    enable: false

clickhouse:
  enable: false

monit:
  vmagent:
    enable: false
  kube_state_metrics:
    enable: false
  node_exporter:
    enable: false
  alertmanager:
    enable: false
  kubedoor_alarm:
    enable: false
  vmalert:
    enable: false
