# kubedoor 1.0.0 开始分为agent端和master端，支持多K8S集群。

# kubedoor-agent需要连接master端的kubedoor-web
# Prometheus/vmagent需要远程写时序数据库

kubedoor:
  agent:
    enable: true
  master:
    ws: "ws://kubedoor-master.kubedoor" # master和agent在同一个K8S，可以直接配置kubedoor-master的service，免认证。
    #ws: "ws://Up4biLko1dNh:qCa22jDkfc9y@10.7.0.226:31027" # 跨K8S访问请使用kubedoor-web外部可访问的地址和端口，并配置认证信息。

config:
  # 这里填写通知的信息，大部分操作会通过该机器人进行通知
  # 钉钉机器人安全设置的自定义关键词请设置为：告警
  MSG_TYPE: "feishu" # 各类操作通知的消息类型：wecom, dingding, feishu
  MSG_TOKEN: "c0021d50-8bc9-4c6c-8857-143cc467305c" # 通知服务对应的token

  #java服务执行dump、jfr、jstack时会把数据存放到OSS，请填写您的OSS地址。（注意设置允许内网免认证上传）
  OSS_URL: "https://xxxxxxxxx.obs.cn-south-1.myhuaweicloud.com"


tsdb:
  # 以下两个字段用于多K8S监控数据，通过远程写方式，写入到同一个时序数据库的场景，即为Prometheus/vmagent设置中的external_labels的key/value。
  # 使用远程存储时，这个key/value会作为标签增加到每一个指标中，这样通过这个标签就可以区分出指标属于哪个K8S了。

  external_labels_key: "origin_prometheus" # 注意key只能字母数字下划线，不能数字开头，不能有中横线和点。注意部署到多套K8S时，请保持external_labels_key都相同，并且与kubedoor-master的也相同。

  # 如果是使用您已有的Prometheus/vmagent，请在您的Prometheus/vmagent配置中找到external_labels的value填入，如果您没有配置过请在您的Prometheus/vmagent配置中新增一个。
  # 如果是kubeDoor为您部署vmagent，请随意填写为您的K8S名称。
  external_labels_value: "kubernetes"


# 【注意】如果您当前K8S已经有完整的Prometheus/vmagent监控，并且是远程写入时序数据库，那么只需要在kubedoor-master配置您的时序数据库信息即可，remoteWriteUrl不用管，并且请把以下所有的enable都设置为false，将不会安装false的组件。
#  详细请参考：https://github.com/CassInfra/KubeDoor/blob/main/docs/灵活部署方案.md#3-接入部署已经有完整的多k8s监控系统

  #【当您需要kubedoor为您安装vmagent时，才需要填写以下地址】注意:Victoria-Metrics-Cluster地址格式：http://你的vminsert地址:8480/insert/0/prometheus
  remoteWriteUrl: "http://monit:dduF1E3sj@victoria-metrics.kubedoor:8428/api/v1/write" # 如果您是使用的kubeDoor安装的Victoria-Metrics，并且当前安装的agent和master在同一个K8S时，【可以直接使用该地址】。否则，请填写您的Victoria-Metrics远程写地址，注意单机的vm的账号密码。


monit:
  # vmagent是比Prometheus性能更好,资源占用更小的指标采集组件。
  vmagent:
    enable: true


  # 用于Prometheus采集K8S监控数据指标，会安装到kubedoor命名空间。
  kube_state_metrics:
    enable: true
    version: v2.14.0


  # 用于Prometheus采集K8S节点数据指标，如果K8S节点已部署node-exporter可设置为false
  node_exporter:
    enable: true
