---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheusalert
  namespace: monitoring
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storage

