{{- if .Values.kubedoor.master.enable }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedoor-mcp
  namespace: kubedoor
  labels:
    app: kubedoor-mcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubedoor-mcp
  template:
    metadata:
      labels:
        app: kubedoor-mcp
    spec:
      containers:
        - name: kubedoor-mcp
          image: {{ .Values.image.repository }}/kubedoor-mcp:{{ .Values.image.kubedoor_mcp_tag }}
          env:
            - name: TZ
              value: Asia/Shanghai
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 1m
              memory: 1Mi
          livenessProbe:
            tcpSocket:
              port: 8000
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 8000
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          imagePullPolicy: Always
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: kubedoor-mcp
  namespace: kubedoor
  labels:
    app: kubedoor-mcp
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app: kubedoor-mcp
  type: NodePort
  externalTrafficPolicy: Cluster 
{{- end }}
