apiVersion: v1
kind: Service
metadata:
  name: kafka-hs
  namespace: midplatform
spec:
  ports:
  - name: broker
    port: 9092
    protocol: TCP
    targetPort: 9092
  - name: jmx
    port: 9999
    protocol: TCP
    targetPort: 9092
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/name: kafka
  type: ClusterIP
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-cs
  namespace: midplatform
spec:
  ports:
  - name: broker
    port: 9092
    protocol: TCP
    targetPort: 9092
  - name: jmx
    port: 9999
    protocol: TCP
    targetPort: 9999
  selector:
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/name: kafka
  type: ClusterIP
