---
apiVersion: v1
kind: Service
metadata:
  name: gitblit
  namespace: devops
spec:
  selector:
    app: gitblit
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: https
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: git-protocol
      port: 9418
      protocol: TCP
      targetPort: 9418
    - name: ssh
      port: 29418
      protocol: TCP
      targetPort: 29418
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitblit
  namespace: devops
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "1024m"
  labels:
    app: gitblit
spec:
  ingressClassName: nginx
  rules:
  - host: gitblit.github.icu
    http:
      paths:
      - backend:
          service:
            name: gitblit
            port:
              number: 8443
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - gitblit.github.icu
    secretName: github-tls
