---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pichome
  namespace: tools
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: moosefs-storage
