---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pichome
  namespace: tools
spec:
  resources:
    requests:
      storage: 20Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storage
