---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  namespace: mysql
spec:
  resources:
    requests:
      storage: 50Gi
  accessModes:
    - ReadWriteMany
  storageClassName: moosefs-storage

