{{- if .Values.kubedoor.master.enable }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: kubedoor
data:
  config.yml: |-
    global:
      resolve_timeout: 10m
    route:
      group_by: [...]
      group_wait: 0s
      group_interval: 30s
      repeat_interval: 30m
      receiver: kubedoor-alarm
      routes:
      - receiver: kubedoor-clickhouse
        group_by: [...]
        group_wait: 0s
        group_interval: 30s
        repeat_interval: 30m
        continue: true
        match_re:
          alertname: K8S_Pod.*

      - receiver: kubedoor-alarm
        group_by: ['{{ .Values.tsdb.external_labels_key }}','namespace','alertname']
        group_wait: 15s
        group_interval: 30s
        repeat_interval: 30m
        continue: false
        match_re:
          alertname: .*

    receivers:
    - name: 'kubedoor-clickhouse'
      webhook_configs:
      - url: 'http://kubedoor-alarm.kubedoor/clickhouse'
        send_resolved: true

    - name: 'kubedoor-alarm'
      webhook_configs:
      - url: 'http://kubedoor-alarm.kubedoor/msg/{{ .Values.config.MSG_TYPE }}={{ .Values.config.MSG_TOKEN }}'
        send_resolved: true
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: kubedoor
  labels:
    app: alertmanager
spec:
  selector:
    app: alertmanager
  type: NodePort
  ports:
    - name: web
      port: 9093
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: kubedoor
  labels:
    app: alertmanager
spec:
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      volumes:
        - name: alertcfg
          configMap:
            name: alertmanager-config
      containers:
        - name: alertmanager
          image: registry.cn-shenzhen.aliyuncs.com/starsl/alertmanager:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: Asia/Shanghai
          args:
            - "--config.file=/etc/alertmanager/config.yml"
            - "--cluster.listen-address="
          ports:
            - containerPort: 9093
              name: http
          volumeMounts:
            - mountPath: "/etc/alertmanager"
              name: alertcfg
          resources:
            limits:
              cpu: '2'
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 256Mi
{{- end }}
