{{- if .Values.clickhouse.enable }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-config
  namespace: kubedoor
data:
  config.xml: |
    <clickhouse replace="true">
        <latency_log remove="1"/>
        <trace_log remove="1"/>
        <processors_profile_log remove="1"/>
        <metric_log remove="1"/>
        <asynchronous_metric_log remove="1"/>
        <query_log remove="1"/>
        <text_log remove="1"/>
        <part_log remove="1"/>
        <asynchronous_metrics_update_period_s>3600</asynchronous_metrics_update_period_s>
        <asynchronous_heavy_metrics_update_period_s>3600</asynchronous_heavy_metrics_update_period_s> 
        <logger>
            <level>warning</level>
            <console>true</console>
        </logger>
        <display_name>chdb_kubedoor</display_name>
        <listen_host>0.0.0.0</listen_host>
        <http_port>8123</http_port>
        <tcp_port>9000</tcp_port>
        <interserver_http_port>9009</interserver_http_port>
        <interserver_listen_host>0.0.0.0</interserver_listen_host>
        <!-- 系统缓存配置 -->
        <mark_cache_size>268435456</mark_cache_size> <!-- 256MB -->
        <uncompressed_cache_size>134217728</uncompressed_cache_size> <!-- 128MB -->
        
        <user_directories>
            <users_xml>
                <path>users.xml</path>
            </users_xml>
            <local_directory>
                <path>/var/lib/clickhouse/access/</path>
            </local_directory>
        </user_directories>
    </clickhouse>

  users.xml: |
    <?xml version="1.0"?>
    <clickhouse replace="true">
        <profiles>
            <default>
                <!-- 外部排序/聚合阈值 -->
                <max_bytes_before_external_group_by>400000000</max_bytes_before_external_group_by> <!-- 400MB -->
                <max_bytes_before_external_sort>400000000</max_bytes_before_external_sort> <!-- 400MB -->
                
                <!-- 内存高效处理 -->
                <distributed_aggregation_memory_efficient>1</distributed_aggregation_memory_efficient>
                <aggregation_memory_efficient_merge_threads>2</aggregation_memory_efficient_merge_threads>
                <enable_memory_bound_merging_of_aggregation_results>1</enable_memory_bound_merging_of_aggregation_results>
                
                <!-- 性能优化 -->
                <local_filesystem_read_method>pread</local_filesystem_read_method>
                <use_uncompressed_cache>0</use_uncompressed_cache>
                <load_balancing>in_order</load_balancing>
                
                <!-- 查询超时控制 -->
                <max_execution_time>300</max_execution_time> <!-- 5分钟查询超时 -->
                <timeout_before_checking_execution_speed>10</timeout_before_checking_execution_speed>
                
                <!-- 日志和调试 -->
                <log_queries>0</log_queries>
                <log_query_threads>0</log_query_threads>
                
                <!-- 网络和连接 -->
                <max_concurrent_queries_for_user>30</max_concurrent_queries_for_user>
                
                <!-- 内存过载保护 -->
                <memory_usage_overcommit_max_wait_microseconds>5000000</memory_usage_overcommit_max_wait_microseconds>
            </default>
        </profiles>
        
        <users>
            <default>
                <password remove='1' />
                <password_sha256_hex>{{ .Values.clickhouse.CK_PASSWORD | sha256sum }}</password_sha256_hex>
                <access_management>1</access_management>
                <profile>default</profile>
                <networks>
                    <ip>0.0.0.0/0</ip>
                </networks>
                <quota>default</quota>
                <named_collection_control>1</named_collection_control>
                <show_named_collections>1</show_named_collections>
                <show_named_collections_secrets>1</show_named_collections_secrets>
            </default>
        </users>
        
        <quotas>
            <default>
                <interval>
                    <duration>3600</duration>
                    <queries>0</queries>
                    <errors>0</errors>
                    <result_rows>0</result_rows>
                    <read_rows>0</read_rows>
                    <execution_time>0</execution_time>
                </interval>
            </default>
        </quotas>
    </clickhouse>

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse
  namespace: kubedoor
  labels:
    app: clickhouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      initContainers:
        - name: disable-thp
          image: registry.cn-shenzhen.aliyuncs.com/starsl/busybox
          command:
            - /bin/sh
            - '-c'
            - >
              echo 'madvise' > /sys/kernel/mm/transparent_hugepage/enabled ||
              true

              echo 'madvise' > /sys/kernel/mm/transparent_hugepage/defrag ||
              true
          volumeMounts:
            - name: sys
              mountPath: /sys
          securityContext:
            privileged: true
      containers:
        - name: clickhouse
          image: registry.cn-shenzhen.aliyuncs.com/starsl/clickhouse-server:25.10-alpine
          ports:
            - containerPort: 8123
            - containerPort: 9000
          env:
            - name: TZ
              value: "Asia/Shanghai"
            - name: CLICKHOUSE_DB
              value: "kubedoor"
            - name: CLICKHOUSE_USER
              value: {{ .Values.clickhouse.CK_USER | quote }}
            - name: CLICKHOUSE_PASSWORD
              value: {{ .Values.clickhouse.CK_PASSWORD | quote }}
            - name: CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT
              value: "1"
          volumeMounts:
            - name: storage
              mountPath: /var/lib/clickhouse
            - name: clickhouse-config
              mountPath: /etc/clickhouse-server/config.d/config.xml
              subPath: config.xml
            - name: clickhouse-config
              mountPath: /etc/clickhouse-server/users.d/users.xml
              subPath: users.xml
          resources:
            limits:
              cpu: "2"
              memory: 4Gi
            requests:
              cpu: 200m
              memory: 1Gi
          startupProbe:
            tcpSocket:
              port: 9000
            timeoutSeconds: 3
            periodSeconds: 10
            failureThreshold: 20
          readinessProbe:
            tcpSocket:
              port: 9000
            timeoutSeconds: 3
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
      restartPolicy: Always
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: kubedoor-clickhouse-data
        - name: clickhouse-config
          configMap:
            name: clickhouse-config
        - name: sys
          hostPath:
            path: /sys
            type: Directory
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubedoor-clickhouse-data
  namespace: kubedoor
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.clickhouse.storage }}
  storageClassName: {{ .Values.storageClass }}

---

apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: kubedoor
  labels:
    app: clickhouse
spec:
  ports:
  - port: 8123
    targetPort: 8123
    protocol: TCP
    name: http
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: tcp
  selector:
    app: clickhouse
  type: ClusterIP

{{- end }}
