---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: knowstreaming
  namespace: knowstreaming
spec:
  resources:
    requests:
      storage: 50Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storage

