apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: knowstreaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - env:
        - name: TZ
          value: Asia/Shanghai
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        - name: MYSQL_DATABASE
          value: know_streaming
        - name: MYSQL_ROOT_HOST
          value: '%'
        image: knowstreaming/knowstreaming-mysql:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 3306
          timeoutSeconds: 1
        name: mysql
        ports:
        - containerPort: 3306
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 3306
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 512Mi
        startupProbe:
          failureThreshold: 20
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 3306
        volumeMounts:
        - mountPath: /etc/localtime
          name: localtime
        - mountPath: /data/mysql
          name: mysql
          subPath: knowstreaming/mysql/data
      volumes:
      - hostPath:
          path: /etc/localtime
          type: ""
        name: localtime
      - name: mysql
        persistentVolumeClaim:
          claimName: knowstreaming
