apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: knowstreaming
  labels:
    app: mysql
spec:
  ports:
  - name: tcp
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: knowstreaming
  labels:
    app: elasticsearch
spec:
  ports:
  - name: http
    port: 9200
    protocol: TCP
    targetPort: 9200
  - name: transport
    port: 9300
    protocol: TCP
    targetPort: 9300
  selector:
    app: elasticsearch
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: knowstreaming-manager
  namespace: knowstreaming
  labels:
    app: knowstreaming-manager
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: knowstreaming-manager
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: knowstreaming-ui
  namespace: knowstreaming
  labels:
    app: knowstreaming-ui
spec:
  ports:
  - name: tcp
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: knowstreaming-ui
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: knowstreaming
  namespace: knowstreaming
  labels:
    app: knowstreaming
spec:
  ingressClassName: nginx
  rules:
  - host: knowstreaming.github.icu
    http:
      paths:
      - backend:
          service:
            name: knowstreaming-ui
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - knowstreaming.github.icu
    secretName: github-tls
