apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  namespace: midplatform
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: zookeeper
      app.kubernetes.io/name: zookeeper
  replicas: 3
  serviceName: zookeeper-hs
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: zookeeper
        app.kubernetes.io/name: zookeeper
    spec:
      containers:
      - name: zookeeper
        command:
        - sh
        - -c
        - "start-zookeeper \
          --servers=3 \
          --data_dir=/var/lib/zookeeper/data \
          --data_log_dir=/var/lib/zookeeper/datalog \
          --conf_dir=/opt/zookeeper/conf \
          --client_port=2181 \
          --election_port=3888 \
          --server_port=2888 \
          --tick_time=2000 \
          --init_limit=10 \
          --sync_limit=5 \
          --heap=512M \
          --max_client_cnxns=60 \
          --snap_retain_count=3 \
          --purge_interval=12 \
          --max_session_timeout=40000 \
          --min_session_timeout=4000 \
          --log_level=INFO"
        image: leolee32/kubernetes-library:kubernetes-zookeeper1.0-3.4.10
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "zookeeper-ready 2181"
          initialDelaySeconds: 10
          timeoutSeconds: 10
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "zookeeper-ready 2181"
          initialDelaySeconds: 10
          timeoutSeconds: 10
        securityContext:
          privileged: true
          runAsUser: 1000
          runAsGroup: 1000
        ports:
        - containerPort: 2181
          name: client
          protocol: TCP
        - containerPort: 2888
          name: server
          protocol: TCP
        - containerPort: 3888
          name: leader-election
          protocol: TCP
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
        - mountPath: /var/lib/zookeeper/data
          name: data
          subPath: zookeeper/data
        - mountPath: /var/lib/zookeeper/datalog
          name: data
          subPath: zookeeper/datalog
      initContainers:
      - name: chmod-data-dir
        image: busybox
        command: [chmod ,'777', -R ,/var/lib/zookeeper/]
        volumeMounts:
          - name: data
            mountPath: /var/lib/zookeeper/data
            subPath: zookeeper/data
          - name: data
            mountPath: /var/lib/zookeeper/datalog
            subPath: zookeeper/datalog
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
            type: ""
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
      storageClassName: moosefs-storage
      volumeMode: Filesystem
