apiVersion: v1
kind: Service
metadata:
  labels:
    app: frpc
  name: frpc
  namespace: tools
spec:
  ports:
  - name: client
    port: 7400
    protocol: TCP
    targetPort: 7400
  selector:
    app: frpc
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frpc
  namespace: tools
  labels:
    app: frpc
spec:
  ingressClassName: nginx
  rules:
  - host: frpc.github.icu
    http:
      paths:
      - backend:
          service:
            name: frpc
            port:
              number: 7400
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - frpc.github.icu
    secretName: github-tls
