apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frps
  name: frps
  namespace: tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frps
  template:
    metadata:
      labels:
        app: frps
    spec:
      containers:
      - name: frps
        image: snowdreamtech/frps:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 7000
          timeoutSeconds: 3
        ports:
        - containerPort: 7000
          name: client
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 7000
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 200m
            memory: 250Gi
          requests:
            cpu: 100m
            memory: 125Mi
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - mountPath: /etc/localtime
          name: localtime
        - mountPath: /etc/frp/frps.toml
          name: frps-config
          subPath: frps.toml
      volumes:
      - hostPath:
          path: /etc/localtime
          type: ""
        name: localtime
      - name: frps-config
        configMap:
          name: frps-config
