---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-ui
  namespace: devops
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: moosefs-storage
