---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ui
  namespace: devops
  labels:
    app: nginx-ui
spec:
  sessionAffinity: ClientIP
  selector:
    app: nginx-ui
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
    - name: https
      protocol: TCP
      port: 443
    - name: web
      protocol: TCP
      port: 9000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ui
  namespace: devops
  labels:
    app: nginx-ui
spec:
  ingressClassName: nginx
  rules:
  - host: nginx-ui.github.icu
    http:
      paths:
      - backend:
          service:
            name: nginx-ui
            port:
              number: 9000
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - nginx-ui.github.icu
    secretName: github-tls
