---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drawdb
  namespace: tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drawdb
  template:
    metadata:
      labels:
        app: drawdb
    spec:
      containers:
        - name: drawdb
          image: avmesquita/drawdb:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: web
              protocol: TCP
          resources:
            limits:
              cpu: "0.5"
              memory: 50Mi
            requests:
              cpu: "0.25"
              memory: 25Mi
          livenessProbe:
            httpGet:
              port: 80
              path: /
            initialDelaySeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10
          readinessProbe:
            httpGet:
              port: 80
              path: /
            initialDelaySeconds: 10
          volumeMounts:
            - mountPath: /etc/localtime
              name: localtime
      volumes:
        - hostPath:
            path: /etc/localtime
            type: ""
          name: localtime
