---
apiVersion: v1
kind: Service
metadata:
  name: drawdb
  namespace: tools
  labels:
    app: drawdb
spec:
  selector:
    app: drawdb
  type: ClusterIP
  ports:
    - port: 80
      name: web
      targetPort: 80
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: drawdb
  namespace: tools
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "5000m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
  labels:
    app: drawdb
spec:
  ingressClassName: nginx
  rules:
  - host: drawdb.github.icu
    http:
      paths:
      - backend:
          service:
            name: drawdb
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - drawdb.github.icu
    secretName: github-tls
