---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis
  namespace: database
spec:
  resources:
    requests:
      storage: 50Gi
  accessModes:
    - ReadWriteMany
  storageClassName: moosefs-storage

