---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openspeedtest
  namespace: tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openspeedtest
  template:
    metadata:
      labels:
        app: openspeedtest
    spec:
      containers:
        - name: openspeedtest
          image: openspeedtest/latest:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
            - containerPort: 3001
              name: https
              protocol: TCP
          resources:
            limits:
              cpu: "0.5"
              memory: 50Mi
            requests:
              cpu: "0.25"
              memory: 25Mi
          livenessProbe:
            httpGet:
              port: 3000
              path: /
            initialDelaySeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10
          readinessProbe:
            httpGet:
              port: 3000
              path: /
            initialDelaySeconds: 10
          volumeMounts:
            - mountPath: /etc/localtime
              name: localtime
      volumes:
        - hostPath:
            path: /etc/localtime
            type: ""
          name: localtime
