---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vector
  namespace: devops
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storage
