---
apiVersion: v1
kind: Service
metadata:
  name: vector
  namespace: devops
  labels:
    app: vector
spec:
  sessionAffinity: ClientIP
  selector:
    app: vector
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8686
