apiVersion: apps/v1
kind: Deployment
metadata:
  name: xxl-job-admin
  namespace: midplatform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xxl-job-admin
  template:
    metadata:
      labels:
        app: xxl-job-admin
    spec:
      containers:
      - env:
        - name: PARAMS
          value: --spring.datasource.url=jdbc:mysql://mysql.github.icu:3306/xxl_job?Unicode=true&characterEncoding=UTF-8&useSSL=false
                 --spring.datasource.username=xxl_job_user --spring.datasource.password=xxl_job
        image: xuxueli/xxl-job-admin:2.4.0
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/bash
              - -c
              - sleep 10
        livenessProbe:
          failureThreshold: 5
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 1
        name: xxl-job-admin
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 512Mi
        startupProbe:
          failureThreshold: 20
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 8080
        volumeMounts:
        - mountPath: /etc/localtime
          name: localtime
      volumes:
      - hostPath:
          path: /etc/localtime
          type: ""
        name: localtime
