apiVersion: v1
kind: Service
metadata:
  name: xxl-job-admin
  namespace: midplatform
  labels:
    app: xxl-job-admin
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: xxl-job-admin
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xxl-job-admin
  namespace: midplatform
  labels:
    app: xxl-job-admin
spec:
  ingressClassName: nginx
  rules:
  - host: xxl.github.icu
    http:
      paths:
      - backend:
          service:
            name: xxl-job-admin
            port:
              number: 8080
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - xxl.github.icu
    secretName: github-tls
